name: moonlight_bay_ui
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  fluro:
    path: ../fluro
  dio: ^5.6.0
  flutter_svg: ^2.0.7



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:


  uses-material-design: true

  assets:
    - Svg/add.svg
    - Svg/channel.svg
    - Svg/edit.svg
    - Svg/move.svg
    - Svg/order.svg
    - Svg/pauseCircle.svg
    - Svg/playCircle.svg
    - Svg/remove.svg
    - Svg/script.svg
    - Svg/setting.svg
    - Svg/stopCircle.svg
    - Svg/terminal.svg



  fonts:
    - family: MiSans
      fonts:
        - asset: fonts/MiSans-Bold.ttf
        - asset: fonts/MiSans-Medium.ttf
        - asset: fonts/MiSans-Normal.ttf

